name: flutter_task
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  flutter_svg: ^2.0.17
  mobx: ^2.5.0
  flutter_mobx: ^2.0.0
  mobx_codegen: ^2.7.0
  lottie: ^3.3.1
  flutter_launcher_icons: ^0.14.3
  animated_splash_screen: ^1.3.0



dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  shared_preferences: ^2.5.2

flutter:

  uses-material-design: true

  assets:
    - lib/assets/img/
    - lib/assets/svg/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "lib/assets/img/Logo.png"
  background_color: "#1434ea"

flutter_intl:
  enabled: true